config/routes.rb
Rails.application.routes.draw do
  devise_for :user, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  get '/', to: "user#index"
  resources :user
  resources :blog
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :content, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum is_admin: [:false, :true]
  enum status: %i[block non_block]

  validates :email, presence: true
  validates :password, presence: true, confirmation: true

  scope :is_not_admin, -> { where(is_admin: is_admins[:false]) }
  scope :status_non_block, -> { where(status: statuses[:non_block]) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @interactor = Blog::Index.call
  end

  def new
    @blog = Blog.new
  end

  def create
    interactor = Blog::Add.call(params: blog_params)
    @blog = interactor.blog
    render :new unless @blog.valid?
  end

  def edit
    interactor = Blog::Show.call(params)
    @blog = interactor.blog
  end

  def update
    interactor = Blog::Edit.call(id: params[:id], params: blog_params)
    @blog = interactor
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :description, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	around_action :set_locale
	before_action :authenticate_user!
	def index
		flash[:notice] = t(:hello)
	end

	private
	def set_locale(&action)
		begin
			locale = params[:locale] || I18n.default_locale
			I18n.with_locale(locale, &action)
			yield
		ensure

		end
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  def index
    @interactor = User::Index.call
  end

  def new
    @user = User.new
  end

  def create
    interactor = User::Add.call(params: user_params)
    @user = interactor.user
    render :new unless @user.valid?
  end

  def edit
    interactor = User::Show.call(params)
    @user = interactor.user
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blog/_form.html.erb
<%= @blog.id ? "edit" : "add"%>
<%= form_with url: @blog.id ? blog_path(@blog) : blog_index_path, model: @blog, method: @blog.id ? :patch : :post do |form| %>
  <div class="form-group">
    <%= form.label :title, "Title" %>
    <%= form.text_field :title, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= form.label :description, "Description" %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :content, "Content" %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>
  <button type="submit" class="btn btn-primary">Add</button>
<% end %>

app/views/blog/edit.html.erb
<%= link_to "Back", blog_index_path, class: "btn" %>
<br/>
<ul>
  <% @blog&.errors&.each do |error| %>
    <li><%= error.full_message %></li>
  <% end %>
</ul>
<div class="col-lg-12">
  <%= render partial: "form", blog: @blog %>
</div>

app/views/blog/index.html.erb
<%= link_to :Add, new_blog_path, class: "btn btn-primary my-2" %>
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Title</th>
    <th scope="col">Created at</th>
    <th scope="col">Updated at</th>
  </tr>
  </thead>
  <tbody>
  <% @interactor.blogs&.each_with_index do |blog| %>
    <tr>
      <td><%= blog.id %></td>
      <td><%= link_to  blog.title, edit_blog_path(blog) %></td>
      <td><%= blog.created_at %></td>
      <td><%= blog.updated_at %></td>
    </tr>
  <% end  %>
  </tbody>
</table>

app/views/blog/new.html.erb
<%= link_to "Back", blog_index_path, class: "btn" %>
<br/>
<ul>
  <% @blog&.errors&.each do |error| %>
    <li><%= error.full_message %></li>
  <% end %>
</ul>
<div class="col-lg-12">
  <%= render partial: "form", blog: @blog %>
</div>

app/views/home/index.html.erb
<h1>Hello rails</h1>
<p><%= flash[:notice] %></p>
<%= t('name', name: "son", default: "this is default message") %>
<%= t('people', count: 1) %>
<%= l Time.now, format: :short, locale: :vi %>

app/views/layouts/_menu.html.erb
<nav class="nav">
  <%= link_to :Home, '/', class: 'nav-link' %>
  <%= link_to :User, user_index_url, class: 'nav-link' %>
  <%= link_to :Blog, blog_index_url, class: 'nav-link' %>
  <%= link_to :Logout, destroy_user_session_path, class: 'nav-link' %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= render partial: 'layouts/menu' %>
    <div class="row">
      <%= yield %>
    </div>
  </div>

  </body>
</html>

app/views/user/_form.html.erb
<%= form_with url: user_index_path, model: @user, method: :post do |form| %>
  <div class="form-group">
    <%= form.label :email, "Email address" %>
    <%= form.text_field :email, type: :email, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= form.label :password, "Password" %>
    <%= form.text_field :password, type: :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :re_password, "Re-password" %>
    <%= form.text_field :password_confirmation, type: :password, class: "form-control" %>
  </div>
  <button type="submit" class="btn btn-primary">Add</button>
<% end %>

app/views/user/edit.html.erb
<%= link_to "Back", user_index_path, class: "btn" %>
<br/>

<div class="col-lg-12">
  <%= render "form", user: @user %>
</div>

app/views/user/index.html.erb
<%= link_to :Add, new_user_path, class: "btn btn-primary my-2" %>
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Email</th>
    <th scope="col">Created at</th>
    <th scope="col">Updated at</th>
  </tr>
  </thead>
  <tbody>
  <% @interactor.users.each_with_index do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= link_to  user.email, edit_user_path(user) %></td>
    <td><%= user.created_at %></td>
    <td><%= user.updated_at %></td>
  </tr>
    <% end  %>
  </tbody>
</table>

app/views/user/new.html.erb
<%= link_to "Back", user_index_path, class: "btn" %>
<br/>
<ul>
  <% @user.errors.each do |error| %>
    <li><%= error.full_message %></li>
  <% end %>
</ul>
<div class="col-lg-12">
<%= render partial: "form", user: @user %>
</div>